require 'spec_helper'
require 'debug'
require 'bundler'
require 'fileutils'
require 'open3'

RSpec.describe 'Fix DB Schema Conflicts' do

  let(:expected_lines) { reference_db_schema.lines }

  it 'generates a sorted schema with no extra spacing' do
    test_app_path = File.expand_path('../test-app', __dir__)
    schema_path = File.join(test_app_path, 'db/schema.rb')
    test_app_gemfile = File.join(test_app_path, 'Gemfile')

    FileUtils.rm_f(schema_path)

    stdout, stderr, status = Open3.capture3('rails', 'db:migrate', chdir: test_app_path)

    expect(status.success?).to be(true)

    expect(File.exist?(schema_path)).to be(true), 'schema.rb was not generated by migration tasks'

    generated_lines = File.readlines(schema_path)

    generated_lines.zip(expected_lines).each do |generated, expected|
      next if expected.nil?
      next if expected.start_with?('ActiveRecord::Schema.define')
      expect(generated).to eq(expected)
    end
  end
end

def reference_db_schema
  <<-RUBY
# This file is auto-generated from the current state of the database. Instead
# of editing this file, please use the migrations feature of Active Record to
# incrementally modify your database, and then regenerate this schema definition.
#
# This file is the source Rails uses to define your schema when running `bin/rails
# db:schema:load`. When creating a new database, `bin/rails db:schema:load` tends to
# be faster and is potentially less error prone than running all of your
# migrations from scratch. Old migrations may fail to apply correctly if those
# migrations use external dependencies or application code.
#
# It's strongly recommended that you check this file into your version control system.

ActiveRecord::Schema[8.0].define(version: 2026_04_27_204352) do
  create_table "companies", force: :cascade do |t|
    t.string "addr1"
    t.string "addr2"
    t.string "city"
    t.datetime "created_at", null: false
    t.string "name"
    t.string "phone"
    t.string "state"
    t.datetime "updated_at", null: false
    t.string "zip"
    t.index ["city"], name: "index_companies_on_city"
    t.index ["name"], name: "index_companies_on_name"
    t.index ["state"], name: "index_companies_on_state"
  end

  create_table "people", force: :cascade do |t|
    t.integer "age"
    t.date "birthdate"
    t.datetime "created_at", null: false
    t.string "first_name"
    t.string "last_name"
    t.datetime "updated_at", null: false
  end
  RUBY
end
